---
salt_repo_url: https://repo.saltstack.com/yum/redhat/salt-repo-latest.el7.noarch.rpm
salt_key_url: https://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest/SALTSTACK-GPG-KEY.pub
apt_repo_name: deb http://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest xenial main 
salt_master: centos7.0-master

