---
# scp this sudo.yml file to target node
# run this file as root user
# ansible-playbook sudo.yml
- hosts: all
  become: true
  gather_facts: yes

  tasks:
  - name: Adding user
    user:
      name: "{{ username }}"
      state: present

  - name: Adding Public key for user
    authorized_key:
      user: "{{ username }}"
      state: present
      key: "{{ item }}"
    with_items:
      - "{{ public_key }}"

  - name: Install packages
    package:
      name: [ 'sudo',
        'openssh-server',
        'ansible' ]
      state: latest
      update_cache: yes
    when: ansible_os_family == "RedHat" or
      ansible_distribution == "Ubuntu" or
      ansible_os_family == "Suse"
    tags: pkg

  - name: Install packages sudo in freebsd
    pkgng:
      name: sudo
      state: latest
    when: ansible_distribution == "FreeBSD"

  - name: Giving sudo right with no passwd to user in CentOS Ubuntu Opensuse
    lineinfile:
      path: /etc/sudoers.d/10_{{ username }}
      line: "{{ username }} ALL=(ALL) NOPASSWD: ALL"
      create: yes
      state: present
    when: ansible_distribution == "CentOS" or
          ansible_distribution == "Ubuntu" or
          ansible_os_family == "Suse"

  - name: Touching user file in /etc/sudoers.d in FreeBSD
    file:
      path: /usr/local/etc/sudoers.d/10_{{ username }}
      state: touch
    when: ansible_distribution == "FreeBSD"

  - name: Giving sudo right with no passwd to user in FreeBSD
    lineinfile:
      path: /usr/local/etc/sudoers.d/10_{{ username }}
      line: "{{ username }} ALL=(ALL) NOPASSWD: ALL"
    when: ansible_distribution == "FreeBSD"

  - name: Run openssh-server
    service:
      name: sshd
      enabled: true
      state: started
