---
# this is an yml to deployment environment by r10k in puppet master.
# ansible-playbook -i inventories/hosts deployment.yml -e "env=devel"
- hosts: puppetmaster
  become: yes
  become_user: root
  gather_facts: yes
  vars:
    env: "{{ env }}"
    cmd: '/opt/puppetlabs/puppet/bin/r10k' 
    config_file: '/etc/puppetlabs/r10k/r10k.yml'

  tasks:
  - name: Deploying environment
    command: /opt/puppetlabs/puppet/bin/r10k --config=/etc/puppetlabs/r10k/r10k.yml deploy environment "{{ env }}"
