---
- hosts: jumphost
  become: yes
  gather_facts: yes
  ignore_errors: yes

  tasks:
    - name: Install grafana Centos or Rocky
      yum:
        name: ['grafana']
        state: latest
        update_cache: yes
      when: ansible_distribution == "CentOS" or
            ansible_distribution == "Rocky"

    - name: Open port 3000 for grafana server
      firewalld:
        permanent: yes
        immediate: yes
        port: 3000/tcp
        state: enabled

    - name: Run grafana server
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items:
        - grafana-server

    - name: Locate your browser on following
      debug:
        msg: Browse http://{{ ansible_default_ipv4.address}}:3000 as user admin

  handlers:
    - name: Restart grafana
      service:
        name: grafana-server
        state: restarted
