# this yml will populate all hosts in the environment 
# to the each hosts' /etc/hosts file
---
- hosts: all
  become: yes
  gather_facts: yes

  tasks:
  - name: Populate followings hosts entry in /etc/hosts
    blockinfile:
      path: /etc/hosts
      block: |
        192.168.180.130 jenkin
        192.168.180.130 jumphost
        192.168.180.130 grafana
        192.168.180.130 nagios

        10.187.4.146 puppetmaster
        10.187.4.136 saltmaster
        10.187.4.84 net-dev1
        10.187.4.200 net-dev2
        10.187.4.17 net-prod1
        10.187.4.249 net-prod2
        10.187.4.150 sys-dev1
        10.187.4.86 sys-dev2
        10.187.4.70 sys-prod1
        10.187.4.217 sys-prod2
