# this yml will populate all hosts in the environment
# to the each hosts' /etc/hosts file
---
- hosts: all
  become: yes
  gather_facts: yes

  tasks:
  - name: Populate followings hosts entry in /etc/hosts
    blockinfile:
      path: /etc/hosts
      block: |
        192.168.180.136 jenkins
        192.168.180.136 jumphost
        192.168.180.136 suse

        10.91.203.114 monitoring
        10.91.203.137 net-dev1
        10.91.203.163 net-dev2
        10.91.203.147 net-prod1
        10.91.203.222 net-prod2
        10.91.203.219 puppetmaster
        10.91.203.98 saltmaster
        10.91.203.23 sys-dev1
        10.91.203.184 sys-dev2
        10.91.203.177 sys-prod1
        10.91.203.217 sys-prod2
        10.91.203.62 elasticsiem
        10.91.203.16 kibana
