# this yml will populate all hosts in the environment 
# to the each hosts' /etc/hosts file
---
- hosts: all
  become: yes
  gather_facts: yes

  tasks:
  - name: Populate followings hosts entry in /etc/hosts
    blockinfile:
      path: /etc/hosts
      block: | 
        192.168.25.197 centos7.0-master
        192.168.25.212 freebsd-prod
        192.168.25.199 freebsd-devel
        192.168.25.211 cmp1-prod
        192.168.25.215 cmp2-devel
        192.168.25.217 ubuntu16-cmp3
	240.217.0.168  devel-centos7
	240.215.0.145  devel-centos8
	240.215.0.110  devel-ubuntu16
	240.211.0.194  devel-ubuntu18
	240.211.0.96   devel-ubuntu20
	240.211.0.208  prod1-centos7
	240.217.0.62   prod1-ubuntu16
	240.215.0.215  prod2-centos7
	240.217.0.150  prod2-ubuntu16

