# this yml will populate all hosts in the environment 
# to the each hosts' /etc/hosts file
---
- hosts: all
  become: yes
  gather_facts: yes

  tasks:
  - name: Populate followings hosts entry in /etc/hosts
    blockinfile:
      path: /etc/hosts
      block: | 
        centos7.0-master  192.168.25.197
        freebsd-prod     192.168.25.212
        freebsd-devel    192.168.25.199
