---
- hosts: lap-lenovo
  become: true
  gather_facts: true
  ignore_errors: true

  tasks:
    - name: get list of all containers
      command:
        cmd: 'incus list -f csv'
      register: container_list
      changed_when: false
      tags: ['lenovo']
