---
# this playbook will install lxd in all compute nodes
# ansible-playbook -i inventory/hosts lxd.yml
- hosts: compute
  become: yes
  gather_facts: yes
  ignore_errors: yes

  tasks:
  - name: Enable IP forwarding
    sysctl:
      name: net.ipv4.ip_forward
      value: 1
      sysctl_set: true

  - name: Install apt key
    ansible.builtin.get_url:
      url: https://pkgs.zabbly.com/key.asc
      dest: /etc/apt/keyrings/zabbly.asc
    when: ansible_distribution == "Debian"
       or ansible_distribution == 'Ubuntu'

  - name: Install incus repository
    ansible.builtin.template:
      src: template/zabbly-incus.j2
      dest: /etc/apt/sources.list.d/zabbly-incus-stable.sources
      owner: root
      group: root
      mode: '0644'
    when: ansible_os_family == "Debian" and
      ( ansible_distribution_release == "noble" or
        ansible_distribution_release == "bookworm" or
        ansible_distribution_release == 'trixie' )
    tags: zabbly

  - name: Install incus package in redhat or suse
    package:
      name: [ 'incus',
        'incus-tools',
        'incus-client',
        'incus-extra',
        'incus-ui-canonical']
      state: present
      update_cache: true
    when: ansible_os_family == "RedHat"
       or ansible_os_family == "Suse"

  - name: Install incus package in debian
    package:
      name: [ 'incus',
        'btrfs-progs', ]
      state: present
      update_cache: true
    when: ansible_distribution == "Debian"
       or ansible_distribution == 'Ubuntu'

  - name: Install firewalld package
    package:
      name: [
        'firewalld',
        'python3-firewall'
        ]
      state: present
      update_cache: true
    when: ansible_os_family == "Debian"
       or ansible_os_family == "RedHat"
       or ansible_os_family == "Suse"

  - name: Add 8443/tcp port in firewalld
    ansible.posix.firewalld:
      zone: trusted
      port: "{{ incus_port }}"
      permanent: true
      immediate: yes
      state: enabled

  - name: Add incusbr0 interface firewalld
    ansible.posix.firewalld:
      zone: trusted
      interface: "{{ incus_br }}"
      permanent: true
      immediate: yes
      state: enabled

  - name: reload firewalld
    ansible.builtin.service:
      name: firewalld
      state: reloaded
    changed_when: false

  - name: Copy preseed file
    template:
      src: template/preseed.j2
      dest: /tmp/preseed
      mode: 0640

  - name: Run incus service
    service:
      name: 'incus'
      state: started
      enabled: yes
    when: ansible_os_family == "Debian"
       or ansible_os_family == "RedHat"
       or ansible_os_family == "Suse"

  - name: initialize lxd from a preseed file
    shell:
      chdir: /tmp
      cmd: 'cat preseed | incus admin init --preseed'
    changed_when: false
