---
- hosts: compute:hypervisors
  become: true
  gather_facts: true
  ignore_errors: true

  tasks:
    - name: get list of all containers
      command:
        cmd: 'incus list -f csv'
      register: container_list
      tags: ['suse','ubu-lxd']

    - name: start puppetserver container
      command:
        cmd: 'incus launch local:ubu22-packer puppetserver'
      when:
        - '"puppetserver" not in container_list.stdout'
      delegate_to: "{{ lookup('csvfile','{1} file=containers_info.csv delimiter=,','puppetserver') }}"
      delegate_facts: true

    - name: start sys-deb12-dev1 container
      command:
        cmd: 'incus launch local:debian12-packer sys-deb12-dev1'
      when:
        - '"sys-deb12-dev1" not in container_list.stdout'
      delegate_to: "{{ lookup('csvfile','{1} file=containers_info.csv delimiter=,','sys-deb12-dev1') }}"
      delegate_facts: true

    - name: start sys-deb12-dev2 container
      command:
        cmd: 'incus launch local:debian12-packer sys-deb12-dev2'
      when:
        - '"sys-deb12-dev2" not in container_list.stdout'
      delegate_to: "{{ lookup('csvfile','{1} file=containers_info.csv delimiter=,','sys-deb12-dev2') }}"
      delegate_facts: true

    - name: start sys-deb12-prod container
      command:
        cmd: 'incus launch local:debian12-packer sys-deb12-prod'
      when:
        - '"sys-deb12-prod" not in container_list.stdout'
      delegate_to: "{{ lookup('csvfile','{1} file=containers_info.csv delimiter=,','sys-deb12-prod') }}"
      delegate_facts: true

    - name: start sys-deb13-dev1 container
      command:
        cmd: 'incus launch local:debian13-packer sys-deb13-dev1'
      when:
        - '"sys-deb13-dev1" not in container_list.stdout'
      delegate_to: "{{ lookup('csvfile','{1} file=containers_info.csv delimiter=,','sys-deb13-dev1') }}"
      delegate_facts: true

    - name: start sys-deb13-dev2 container
      command:
        cmd: 'incus launch local:debian13-packer sys-deb13-dev2'
      when:
        - '"sys-deb13-dev2" not in container_list.stdout'
      delegate_to: "{{ lookup('csvfile','{1} file=containers_info.csv delimiter=,','sys-deb13-dev2') }}"
      delegate_facts: true

    - name: start sys-deb13-prod container
      command:
        cmd: 'incus launch local:debian13-packer sys-deb13-prod'
      when:
        - '"sys-deb13-prod" not in container_list.stdout'
      delegate_to: "{{ lookup('csvfile','{1} file=containers_info.csv delimiter=,','sys-deb13-prod') }}"
      delegate_facts: true

    - name: start sys-alma9-dev1 container
      command:
        cmd: 'incus launch local:alma9-packer sys-alma9-dev1'
      when:
        - '"sys-alma9-dev1" not in container_list.stdout'
      delegate_to: "{{ lookup('csvfile','{1} file=containers_info.csv delimiter=,','sys-alma9-prod') }}"
      delegate_facts: true

    - name: start sys-alma9-dev2 container
      command:
        cmd: 'incus launch local:alma9-packer sys-alma9-dev2'
      when:
        - '"sys-alma9-dev2" not in container_list.stdout'
      delegate_to: "{{ lookup('csvfile','{1} file=containers_info.csv delimiter=,','sys-alma9-prod') }}"
      delegate_facts: true

    - name: start sys-alma9-prod container
      command:
        cmd: 'incus launch local:alma9-packer sys-alma9-prod'
      when:
        - '"sys-alma9-prod" not in container_list.stdout'
      delegate_to: "{{ lookup('csvfile','{1} file=containers_info.csv delimiter=,','sys-alma9-prod') }}"
      delegate_facts: true

    - name: start sys-ubu22-dev1 container
      command:
        cmd: 'incus launch local:ubu22-packer sys-ubu22-dev1'
      when:
        - '"sys-ubu22-dev1" not in container_list.stdout'
      delegate_to: "{{ lookup('csvfile','{1} file=containers_info.csv delimiter=,','sys-ubu22-dev1') }}"
      delegate_facts: true

    - name: start sys-ubu22-dev2 container
      command:
        cmd: 'incus launch local:ubu22-packer sys-ubu22-dev2'
      when:
        - '"sys-ubu22-dev2" not in container_list.stdout'
      delegate_to: "{{ lookup('csvfile','{1} file=containers_info.csv delimiter=,','sys-ubu22-dev2') }}"
      delegate_facts: true

    - name: start sys-ubu22-prod container
      command:
        cmd: 'incus launch local:ubu22-packer sys-ubu22-prod'
      when:
        - '"sys-ubu22-prod" not in container_list.stdout'
      delegate_to: "{{ lookup('csvfile','{1} file=containers_info.csv delimiter=,','sys-ubu22-prod') }}"
      delegate_facts: true

    - name: start sys-ubu24-dev1 container
      command:
        cmd: 'incus launch local:ubu24-packer sys-ubu24-dev1'
      when:
        - '"sys-ubu24-dev1" not in container_list.stdout'
      delegate_to: "{{ lookup('csvfile','{1} file=containers_info.csv delimiter=,','sys-ubu24-dev1') }}"
      delegate_facts: true

    - name: start sys-ubu24-dev2 container
      command:
        cmd: 'incus launch local:ubu24-packer sys-ubu24-dev2'
      when:
        - '"sys-ubu24-dev2" not in container_list.stdout'
      delegate_to: "{{ lookup('csvfile','{1} file=containers_info.csv delimiter=,','sys-ubu24-dev2') }}"
      delegate_facts: true

    - name: start sys-ubu24-prod container
      command:
        cmd: 'incus launch local:ubu24-packer sys-ubu24-prod'
      when:
        - '"sys-ubu24-prod" not in container_list.stdout'
      delegate_to: "{{ lookup('csvfile','{1} file=containers_info.csv delimiter=,','sys-ubu24-prod') }}"
      delegate_facts: true

    - name: start sys-suse-dev1 container
      command:
        cmd: 'incus launch local:opensuse-packer sys-suse-dev1'
      when:
        - '"sys-suse-dev1" not in container_list.stdout'
      delegate_to: "{{ lookup('csvfile','{1} file=containers_info.csv delimiter=,','sys-suse-dev1') }}"
      delegate_facts: true
      tags: suse

    - name: start sys-suse-dev2 container
      command:
        cmd: 'incus launch local:opensuse-packer sys-suse-dev2'
      when:
        - '"sys-suse-dev2" not in container_list.stdout'
      delegate_to: "{{ lookup('csvfile','{1} file=containers_info.csv delimiter=,','sys-suse-dev2') }}"
      delegate_facts: true
      tags: suse

    - name: start sys-suse-prod container
      command:
        cmd: 'incus launch local:opensuse-packer sys-suse-prod'
      when:
        - '"sys-suse-prod" not in container_list.stdout'
      delegate_to: "{{ lookup('csvfile','{1} file=containers_info.csv delimiter=,','sys-suse-prod') }}"
      delegate_facts: true
      tags: suse
