---
- hosts: compute
  become: true
  gather_facts: true
  ignore_errors: true

  tasks:
    - name: get list of all containers
      command:
        cmd: 'incus list -f csv'
      register: container_list

    - name: start puppetserver container
      command:
        cmd: 'incus launch local:ubu20-packer puppetserver'
      when:
        - '"puppetserver" not in container_list.stdout'

    - name: start sys-deb12-dev1 container
      command:
        cmd: 'incus launch local:debian12-packer sys-deb12-dev1'
      when:
        - '"sys-deb12-dev1" not in container_list.stdout'

    - name: start sys-alma8-dev1 container
      command:
        cmd: 'incus launch local:alma8-packer sys-alma8-dev1'
      when:
        - '"sys-alma8-dev1" not in container_list.stdout'

    - name: start sys-alma9-dev1 container
      command:
        cmd: 'incus launch local:alma9-packer sys-alma9-dev1'
      when:
        - '"sys-alma9-dev1" not in container_list.stdout'

    - name: start sys-ubu20-dev1 container
      command:
        cmd: 'incus launch local:ubu20-packer sys-ubu20-dev1'
      when:
        - '"sys-ubu20-dev1" not in container_list.stdout'

    - name: start sys-ubu20-dev2 container
      command:
        cmd: 'incus launch local:ubu20-packer sys-ubu20-dev2'
      when:
        - '"sys-ubu20-dev2" not in container_list.stdout'

    - name: start sys-ubu20-prod container
      command:
        cmd: 'incus launch local:ubu20-packer sys-ubu20-prod'
      when:
        - '"sys-ubu20-prod" not in container_list.stdout'

    - name: start sys-ubu22-dev1 container
      command:
        cmd: 'incus launch local:ubu22-packer sys-ubu22-dev1'
      when:
        - '"sys-ubu22-dev1" not in container_list.stdout'

    - name: start sys-ubu22-dev2 container
      command:
        cmd: 'incus launch local:ubu22-packer sys-ubu22-dev2'
      when:
        - '"sys-ubu22-dev2" not in container_list.stdout'

    - name: start sys-ubu22-prod container
      command:
        cmd: 'incus launch local:ubu22-packer sys-ubu22-prod'
      when:
        - '"sys-ubu22-prod" not in container_list.stdout'

    - name: start sys-ubu24-dev1 container
      command:
        cmd: 'incus launch local:ubu24-packer sys-ubu24-dev1'
      when:
        - '"sys-ubu24-dev1" not in container_list.stdout'

    - name: start sys-ubu24-dev2 container
      command:
        cmd: 'incus launch local:ubu24-packer sys-ubu24-dev2'
      when:
        - '"sys-ubu24-dev2" not in container_list.stdout'

    - name: start sys-ubu24-prod container
      command:
        cmd: 'incus launch local:ubu24-packer sys-ubu24-prod'
      when:
        - '"sys-ubu24-prod" not in container_list.stdout'
