---
# this playbook will install lxd in all compute nodes
# ansible-playbook -i inventory/hosts lxd.yml
- hosts: compute
  become: yes
  gather_facts: yes
  ignore_errors: yes

  tasks:
  - name: Enable IP forwarding
    sysctl:
      name: net.ipv4.ip_forward
      value: 1
      sysctl_set: true
    when: ansible_os_family == "Debian"
      or ansible_os_family == "Suse"

  - name: Install incus in debian based OS
    apt:
      name: [ 'incus', 'qemu-system', 'incus-tools' ]
      state: present
      update_cache: yes
    when: ansible_os_family == "Debian"
          and ( ansible_distribution_major_version|int == 13
          or ansible_distribution_major_version|int == 24 )

  - name: Install incus in openSuse
    zypper:
      name: [ 'incus', 'qemu-system', 'incus-tools' ]
      state: present
      update_cache: yes
    when: ansible_os_family == "Suse"

  - name: Add lxdbr0 in trusted zone in Firewalld
    firewalld:
      zone: trusted
      interface: lxdbr0
      permanent: true
      state: enabled
    when: ansible_os_family == "Suse"

  - name: Run incus service
    service:
      name: 'incus'
      state: started
      enabled: true

#  - name: Copy preseed file
#    template:
#      src: template/preseed.j2
#      dest: /tmp/preseed
#      mode: 0640
