---
- hosts: compute
  become: true
  gather_facts: true

  tasks:
    - name: get list of all containers
      command:
        cmd: 'incus list -f csv'
      register: container_list

    - name: start sys-alma8-dev1 container
      command:
        cmd: 'incus launch local:alma8-packer sys-alma8-dev1'
      when:
        - '"sys-alma8-dev1" not in container_list.stdout'

    - name: start sys-alma8-dev2 container
      command:
        cmd: 'incus launch local:alma8-packer sys-alma8-dev2'
      when:
        - '"sys-alma8-dev2" not in container_list.stdout'

    - name: start sys-alma8-prod container
      command:
        cmd: 'incus launch local:alma8-packer sys-alma8-prod'
      when:
        - '"sys-alma8-prod" not in container_list.stdout'

    - name: start sys-alma9-dev1 container
      command:
        cmd: 'incus launch local:alma9-packer sys-alma9-dev1'
      when:
        - '"sys-alma9-dev1" not in container_list.stdout'

    - name: start sys-alma9-dev2 container
      command:
        cmd: 'incus launch local:alma9-packer sys-alma9-dev2'
      when:
        - '"sys-alma9-dev2" not in container_list.stdout'

    - name: start sys-alma9-prod container
      command:
        cmd: 'incus launch local:alma9-packer sys-alma9-prod'
      when:
        - '"sys-alma9-prod" not in container_list.stdout'

    - name: start sys-centos9-dev1 container
      command:
        cmd: 'incus launch local:centos9-packer sys-centos9-dev1'
      when:
        - '"sys-centos9-dev1" not in container_list.stdout'

    - name: start sys-centos9-dev2 container
      command:
        cmd: 'incus launch local:centos9-packer sys-centos9-dev2'
      when:
        - '"sys-centos9-dev2" not in container_list.stdout'

    - name: start sys-centos9-prod container
      command:
        cmd: 'incus launch local:centos9-packer sys-centos9-prod'
      when:
        - '"sys-centos9-prod" not in container_list.stdout'

    - name: start sys-rocky8-dev1 container
      command:
        cmd: 'incus launch local:rocky8-packer sys-rocky8-dev1'
      when:
        - '"sys-rocky8-dev1" not in container_list.stdout'

    - name: start sys-rocky8-dev2 container
      command:
        cmd: 'incus launch local:rocky8-packer sys-rocky8-dev2'
      when:
        - '"sys-rocky8-dev2" not in container_list.stdout'

    - name: start sys-rocky8-prod container
      command:
        cmd: 'incus launch local:rocky8-packer sys-rocky8-prod'
      when:
        - '"sys-rocky8-prod" not in container_list.stdout'

    - name: start sys-rocky9-dev1 container
      command:
        cmd: 'incus launch local:rocky9-packer sys-rocky9-dev1'
      when:
        - '"sys-rocky9-dev1" not in container_list.stdout'

    - name: start sys-rocky9-dev2 container
      command:
        cmd: 'incus launch local:rocky9-packer sys-rocky9-dev2'
      when:
        - '"sys-rocky9-dev2" not in container_list.stdout'

    - name: start sys-rocky9-prod container
      command:
        cmd: 'incus launch local:rocky9-packer sys-rocky9-prod'
      when:
        - '"sys-rocky9-prod" not in container_list.stdout'

    - name: start sys-suse-dev1 container
      command:
        cmd: 'incus launch local:opensuse-packer sys-suse-dev1'
      when:
        - '"sys-suse-dev1" not in container_list.stdout'

    - name: start sys-suse-dev2 container
      command:
        cmd: 'incus launch local:opensuse-packer sys-suse-dev2'
      when:
        - '"sys-suse-dev2" not in container_list.stdout'

    - name: start sys-suse-prod container
      command:
        cmd: 'incus launch local:opensuse-packer sys-suse-prod'
      when:
        - '"sys-alma9-prod" not in container_list.stdout'

    - name: start sys-ubu20-dev1 container
      command:
        cmd: 'incus launch local:ubu20-packer sys-ubu20-dev1'
      when:
        - '"sys-ubu20-dev1" not in container_list.stdout'

    - name: start sys-ubu20-dev2 container
      command:
        cmd: 'incus launch local:ubu20-packer sys-ubu20-dev2'
      when:
        - '"sys-ubu20-dev2" not in container_list.stdout'

    - name: start sys-ubu20-prod container
      command:
        cmd: 'incus launch local:ubu20-packer sys-ubu20-prod'
      when:
        - '"sys-ubu20-prod" not in container_list.stdout'
