---
# this playbook will install lxd in all compute nodes
# ansible-playbook -i inventory/hosts lxd.yml
- hosts: compute
  become: yes
  gather_facts: yes
  ignore_errors: yes

  tasks:
  - name: Enable IP forwarding
    sysctl:
      name: net.ipv4.ip_forward
      value: 1
      sysctl_set: true

  - name: Install incus package
    package:
      name: [ 'incus', 'incus-tools' ]
      state: present
      update_cache: true
    when: ansible_os_family == "Debian" or
      ansible_os_family == "RedHat" or
      ansible_os_family == "Suse"

  - name: Run incus service
    service:
      name: 'incus'
      state: started
      enabled: yes
    when: ansible_os_family == "Debian" or
      ansible_os_family == "RedHat" or
      ansible_os_family == "Suse"

  - name: Add 8443/tcp port in firewalld
    ansible.posix.firewalld:
      zone: trusted
      port: "{{ incus_port }}"
      permanent: true
      immediate: yes
      state: enabled

  - name: Add incusbr0 interface firewalld
    ansible.posix.firewalld:
      zone: trusted
      interface: "{{ incus_br }}"
      permanent: true
      immediate: yes
      state: enabled

  - name: reload firewalld
    ansible.builtin.service:
      name: firewalld
      state: reloaded

  - name: Copy preseed file
    template:
      src: template/preseed.j2
      dest: /tmp/preseed
      mode: 0640

  - name: initialize lxd from a preseed file
    shell:
      chdir: /tmp
      cmd: 'cat preseed | incus admin init --preseed'
