---
# this will install a jumphost in localhost
- hosts: localhost:jumphosts
  gather_facts: yes
  become: yes
  ignore_errors: true

  tasks:
  - name: Add public key in authorized_key file
    authorized_key:
      user: "{{ ssh_user }}"
      #key: "{{ public_key }}"
      #key: "{{ lookup('file', {{ item }} ) }}"
      key: "{{ lookup('file', item) }}"
    with_items:
      - "{{ public_keyfile }}"

  - name: Install openssh-server
    apt:
      name: "openssh-server"
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Enable and run openssh-service
    service:
      name: sshd
      enabled: yes
      state: started

  - name: Install firewalld pkg in ubuntu
    apt:
      name: "firewalld"
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Install firewalld pkg in opensuse
    zypper:
      name: "firewalld"
      state: latest
      update_cache: yes
    when: ansible_os_family == "Suse"

  - name: Enable firewalld service
    service:
      name: firewalld
      enabled: true
      state: started

  - name: Enable 8080 port forwarding for nagios
    firewalld:
      rich_rule: rule family=ipv4 forward-port port=8080 protocol=tcp to-port=80 to-addr={{ monitoring_ip }}
      zone: public
      permanent: true
      immediate: true
      state: enabled
    when: ansible_distribution == "Ubuntu"

  - name: Enable 3000 port forwarding for grafana
    firewalld:
      rich_rule: rule family=ipv4 forward-port port=3000 protocol=tcp to-port=3000 to-addr={{ monitoring_ip }}
      zone: public
      permanent: true
      immediate: true
      state: enabled
    when: ansible_distribution == "Ubuntu"

  - name: Enable 9200 port forwarding for elasticsearch
    firewalld:
      rich_rule: rule family=ipv4 forward-port port=9200 protocol=tcp to-port=9200 to-addr={{ elastic_node_ip }}
      zone: public
      permanent: true
      immediate: true
      state: enabled
    when: ansible_distribution == "Ubuntu"

  - name: Enable 5601 port forwarding for kibana
    firewalld:
      rich_rule: rule family=ipv4 forward-port port=5601 protocol=tcp to-port=5601 to-addr={{ kibana_node_ip }}
      zone: public
      permanent: true
      immediate: true
      state: enabled
    when: ansible_distribution == "Ubuntu"
