---
# this playbook will install lxd in all compute nodes
# by using snap. 
# ansible-playbook -i inventory/hosts lxd.yml
- hosts: compute
  become: yes
  gather_facts: yes
  ignore_errors: yes

  tasks:
  - name: Remove some pre install packages
    apt:
      name: [ 'lxd', 'lxd-client' ]
      purge: yes
      state: absent

  - name: Install snapd in Ubuntu
    apt:
      name: [ 'snapd', 'zfsutils-linux' ]
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Insall lxd by snapd in Ubuntu
    snap:
      name: lxd
      state: present

#  - name: Copy preseed file
#    template:
#      src: template/preseed.j2
#      dest: /tmp/preseed
#      mode: 0640
