---
# this script will install lxd container
- hosts: compute
  become: yes
  gather_facts: yes
  ignore_errors: true

  tasks:
  - name: Create a started sys-cent8-dev1 container
    lxd_container:
      name: sys-cent8-dev1
      state: started
      source:
        type: image
        mode: pull
        server: https://images.linuxcontainers.org
        protocol: lxd
        alias: centos/8/amd64
      profiles: ["default"]
      wait_for_ipv4_addresses: true
      timeout: 600

  - name: Create a started sys-ubu20-dev1 container
    lxd_container:
      name: sys-ubu20-dev1
      state: started
      source:
        type: image
        mode: pull
        server: https://images.linuxcontainers.org
        protocol: lxd
        alias: ubuntu/focal/amd64
      profiles: ["default"]
      wait_for_ipv4_addresses: true
      timeout: 600
