---
# this script will install lxd container
- hosts: compute
  become: yes
  gather_facts: yes
  ignore_errors: true

  tasks:
  - name: Create a started saltmaster container
    lxd_container:
      name: saltmaster
      state: started
      source:
        type: image
        mode: pull
        server: https://images.linuxcontainers.org
        protocol: simplestreams
        alias: centos/9-Stream/arm64
      profiles: ["default"]
      wait_for_ipv4_addresses: true
      timeout: 600
    tags: saltmaster

  - name: Create a started sys-prod1 container
    lxd_container:
      name: sys-prod1
      state: started
      source:
        type: image
        mode: pull
        server: https://images.linuxcontainers.org
        protocol: simplestreams
        alias: centos/9-Stream/arm64
      profiles: ["default"]
      wait_for_ipv4_addresses: true
      timeout: 600

  - name: Create a started sys-prod2 container
    lxd_container:
      name: sys-prod2
      state: started
      source:
        type: image
        mode: pull
        server: https://images.linuxcontainers.org
        protocol: simplestreams
        alias: opensuse/tumbleweed/arm64
      profiles: ["default"]
      wait_for_ipv4_addresses: true
      timeout: 600

  - name: Create a started sys-dev1 container
    lxd_container:
      name: sys-dev1
      state: started
      source:
        type: image
        mode: pull
        server: https://images.linuxcontainers.org
        protocol: simplestreams
        alias: centos/9-Stream/arm64
      profiles: ["default"]
      wait_for_ipv4_addresses: true
      timeout: 600

  - name: Create a started sys-dev2 container
    lxd_container:
      name: sys-dev2
      state: started
      source:
        type: image
        mode: pull
        server: https://images.linuxcontainers.org
        protocol: simplestreams
        alias: opensuse/tumbleweed/arm64
      profiles: ["default"]
      wait_for_ipv4_addresses: true
      timeout: 600

  - name: Create a started monitoring container
    lxd_container:
      name: monitoring
      state: started
      source:
        type: image
        mode: pull
        server: https://images.linuxcontainers.org
        protocol: simplestreams
        alias: opensuse/tumbleweed/arm64
      profiles: ["default"]
      wait_for_ipv4_addresses: true
      timeout: 600

  - name: Create a started puppetmaster container
    lxd_container:
      name: puppetmaster
      state: started
      source:
        type: image
        mode: pull
        server: https://images.linuxcontainers.org
        protocol: simplestreams
        alias: debian/bullseye/arm64
      profiles: ["default"]
      wait_for_ipv4_addresses: true
      timeout: 600

  - name: Create a started net-prod1 container
    lxd_container:
      name: net-prod1
      state: started
      source:
        type: image
        mode: pull
        server: https://images.linuxcontainers.org
        protocol: simplestreams
        alias: debian/bullseye/arm64
      profiles: ["default"]
      wait_for_ipv4_addresses: true
      timeout: 600

  - name: Create a started net-prod2 container
    lxd_container:
      name: net-prod2
      state: started
      source:
        type: image
        mode: pull
        server: https://images.linuxcontainers.org
        protocol: simplestreams
        alias: debian/bullseye/arm64
      profiles: ["default"]
      wait_for_ipv4_addresses: true
      timeout: 600

  - name: Create a started net-dev1 container
    lxd_container:
      name: net-dev1
      state: started
      source:
        type: image
        mode: pull
        server: https://images.linuxcontainers.org
        protocol: simplestreams
        alias: debian/bullseye/arm64
      profiles: ["default"]
      wait_for_ipv4_addresses: true
      timeout: 600

  - name: Create a started net-dev2 container
    lxd_container:
      name: net-dev2
      state: started
      source:
        type: image
        mode: pull
        server: https://images.linuxcontainers.org
        protocol: simplestreams
        alias: debian/bullseye/arm64
      profiles: ["default"]
      wait_for_ipv4_addresses: true
      timeout: 600
