---
- hosts: jumphost
  become: yes
  gather_facts: yes
  ignore_errors: yes

  tasks:
    - name: Place Prometheus repo
      template:
        src: template/prometheus.repo.j2
        dest: /etc/yum.repos.d/prometheus.repo
      when: ansible_distribution == "CentOS" or
            ansible_distribution == "Rocky"

    - name: Install Prometheus and related pkgs in Centos or Rocky
      yum:
        name: ['prometheus2', 'node_exporter']
        state: latest
        update_cache: yes
      when: ansible_distribution == "CentOS" or
            ansible_distribution == "Rocky"

    - name: Place Prometheus config yml file
      template:
        src: template/prometheus.yml.j2
        dest: /etc/prometheus/prometheus.yml
      notify:
        - Restart prometheus

    - name: Add prometheus service in Firewalld
      firewalld:
        permanent: yes
        immediate: yes
        service: prometheus
        state: enabled

    - name: Run Prometheus service and node_exporter
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items:
        - prometheus
        - node_exporter

    - name: Locate your browser on following
      debug:
        msg: Browse http://{{ ansible_default_ipv4.address}}:9090

  handlers:
    - name: Restart prometheus
      service:
        name: prometheus
        state: restarted
