---
# quagga will be used to install and configure bgp in compute nodes
# and master. BGP will advertize internal lxdfan0 network of
# compute nodes so that master, nodes and lxd can ping each other.
- hosts: compute:centos7.0-master
  become: yes
  gather_facts: true

  tasks:
  - name: Install quagga package in Ubuntu
    apt:
      name: ['quagga', 'quagga-doc']
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Install quagga package in CentOS
    yum:
      name: ['quagga']
      state: latest
    when: ansible_distribution == "CentOS"

  - name: Placing vtysh configuration files
    template:
      src: template/vtysh.conf.j2
      dest: /etc/quagga/vtysh.conf
      mode: 0640
      owner: quagga
      group: quagga

  - name: Placing daemons configuration files
    template:
      src: template/daemons.j2
      dest: /etc/quagga/daemons
      mode: 0640
      owner: quagga
      group: quagga

  - name: Placing zebra configuration files
    template:
      src: template/zebra.conf.j2
      dest: /etc/quagga/zebra.conf
      mode: 0640
      owner: quagga
      group: quagga

  - name: Placing bgp configuration files
    template:
      src: template/bgpd.conf.j2
      dest: /etc/quagga/bgpd.conf
      mode: 0640
      owner: quagga
      group: quagga

  - name: Running quagga service in Ubuntu
    service:
      name: quagga
      state: started
      enabled: true
    when: ansible_distribution == "Ubuntu"

  - name: Running zebra service in CentOS
    service:
      name: "{{ item }}"
      state: started
      enabled: true
    with_items:
      - zebra
      - bgpd
    when: ansible_distribution == "CentOS"
    tags: service
