- src: https://github.com/masumndc1/ansible-elasticsiem.git
  scm: git
  path: roles
  version: master

- src: https://github.com/masumndc1/ansible-role-packer-incus.git
  scm: git
  path: roles
  version: v1.0.1
