---
- hosts: saltmaster
  become: yes
  gather_facts: yes

  handlers:
    - name: Restart salt-master service
      service:
        name: salt-master
        state: restarted

  tasks:
  - name: install common packages for CentOS
    yum:
      name: "{{ rpm_package }}"
      state: latest
    when: ansible_distribution == "CentOS"

  - name: install salt repo for CentOS
    yum:
      name: "{{ salt_repo_url }}"
      state: latest
    when: ansible_distribution == "CentOS"

  - name: install salt-master 
    yum:
      name: "{{ salt_package }}"
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: Opening firewall ports for saltminion
    firewalld:
      port: "{{ item }}"
      state: enabled
      permanent: yes
    with_items: "{{ salt_port }}"

  - name: Placing configuration files
    template:
      src: template/master_conf.j2
      dest: /etc/salt/master.d/file_gitfs.conf
      mode: '0644'  
    notify:
      - Restart salt-master service

  - name: Create directory for base 
    file:
      path: /srv/salt
      state: directory
      mode: '0644'

  - name: Cloning git repository for state files.
    git: 
      repo: git@github.com:masumndc1/salt-states.git
      dest: /srv/salt

  - name: Run the salt-master service
    service:
      name: salt-master
      enabled: true
      state: started

  tags:
    - salt
