---
# run this playbook with -l saltminion
- hosts: saltminions
  become: yes
  gather_facts: yes

  handlers:
    - name: Restart salt-minion service
      service:
        name: salt-minion
        state: restarted

  tasks:
  - name: install salt repo for CentOS9
    yum_repository:
      name: salt
      description: "Salt repo for RHEL/CentOS 9 PY3"
      baseurl: "{{ centos_repo_url }}"
      enabled: true
      gpgcheck: true
      gpgkey: "{{ centos_salt_key }}"
      state: present
    when: ansible_distribution == "CentOS"

  - name: install common packages for Ubuntu
    apt:
      name: "{{ deb_package }}"
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Add salt key for Ubuntu
    apt_key:
      url: "{{ salt_key_url20 }}"
      state: present
    when: ansible_distribution == "Ubuntu" and
          ansible_distribution_major_version|int == "20"

  - name: Add salt repo for Ubuntu
    apt_repository:
      repo: "{{ apt_repo_name20 }}"
      state: present
      filename: saltstack
    when: ansible_distribution == "Ubuntu" and
          ansible_distribution_major_version|int == "20"

  - name: Add salt key for Ubuntu
    get_url:
      url: "{{ deb_key_url }}"
      dest: /etc/apt/keyrings/salt-archive-keyring.pgp
    when: ansible_distribution == "Ubuntu" and
      ansible_distribution_major_version|int == 24

  - name: Add salt repo for Ubuntu
    get_url:
      url: "{{ deb_repo_url }}"
      dest: /etc/apt/sources.list.d/salt.sources
    when: ansible_distribution == "Ubuntu" and
          ansible_distribution_major_version|int == 24

  - name: Opening firewall ports in saltminions
    ansible.posix.firewalld:
      zone: trusted
      port: "{{ item }}"
      permanent: yes
      immediate: yes
      state: enabled
    with_items: "{{ salt_port }}"
    ignore_errors: true
    when: ansible_distribution == "CentOS" or
          ansible_os_family == "Suse" or
          ansible_distribution == "Ubuntu"

  - name: reload firewalld
    ansible.builtin.service:
      name: firewalld
      state: reloaded

  - name: install salt-minion for centos
    yum:
      name: salt-minion
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: Install salt-minion in Ubuntu
    apt:
      name: salt-minion
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Install salt-minion in Opensuse
    zypper:
      name: salt-minion
      state: latest
      update_cache: yes
    when: ansible_os_family == "Suse"

  - name: Run the salt-minion service
    service:
      name: salt-minion
      enabled: true
      state: started

  - name: Setting salt-master IP in /etc/salt/minion file
    lineinfile:
      path: /etc/salt/minion
      regexp: '^#master:|^master:'
      line: 'master: saltmaster'
    notify:
      - Restart salt-minion service

  - name: Setting minion_id in /etc/salt/minion_id file
    template:
      src: template/minion_id.j2
      dest: /etc/salt/minion_id
      mode: 0644
    notify:
      - Restart salt-minion service

  tags:
    - saltminions
