---
# run this playbook with -l salt on
- hosts: saltmaster
  become: yes
  gather_facts: yes

  handlers:
    - name: Restart salt-master service
      service:
        name: salt-master
        state: restarted

  tasks:
  - name: install salt repo for CentOS
    yum_repository:
      name: salt
      description: "Salt repo for RHEL/CentOS 9 PY3"
      baseurl: "{{ centos_repo_url }}"
      enabled: true
      gpgcheck: true
      gpgkey: "{{ centos_salt_key }}"
      state: present
    when: ansible_distribution == "CentOS"

  - name: install common pkgs for CentOS
    yum:
      name: "{{ item }}"
      state: latest
      update_cache: yes
    with_items:
      - "{{ centos_pkg }}"
    when: ansible_distribution == "CentOS"

  - name: install salt-master for CentOS
    yum:
      name: "{{ salt_package }}"
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install common packages for Ubuntu
    apt:
      name: "{{ deb_package }}"
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Add salt key for Ubuntu
    get_url:
      url: "{{ deb_key_url }}"
      dest: /etc/apt/keyrings/salt-archive-keyring.pgp
    when: ansible_distribution == "Ubuntu"

  - name: Add salt repo for Ubuntu
    get_url:
      url: "{{ deb_repo_url }}"
      dest: /etc/apt/sources.list.d/salt.sources
    when: ansible_distribution == "Ubuntu"

  - name: install salt-master in Ubuntu
    apt:
      name: "{{ salt_package }}"
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install PyGithub in Opensuse
    zypper:
      name: "{{ suse_pkg }}"
      state: latest
      update_cache: yes
    when: ansible_os_family == "Suse"

  - name: install salt-master in Opensuse
    zypper:
      name: "{{ salt_package }}"
      state: latest
      update_cache: yes
    when: ansible_os_family == "Suse"

  - name: Opening firewall ports in saltmaster
    ansible.posix.firewalld:
      zone: trusted
      port: "{{ item }}"
      permanent: yes
      immediate: true
      state: enabled
    with_items: "{{ salt_port }}"
    ignore_errors: true
    when: ansible_distribution == "CentOS" or
          ansible_os_family == "Suse" or
          ansible_distribution == "Ubuntu"

  - name: reload firewalld
    ansible.builtin.service:
      name: firewalld
      state: reloaded

  - name: Create directory for base
    file:
      path: /srv/salt
      state: directory
      mode: '0755'

  - name: Create directory for pillar
    file:
      path: /srv/salt/pillar
      state: directory
      mode: '0755'

  - name: Run the salt-master service
    service:
      name: salt-master
      enabled: true
      state: started

  - name: Place the top file
    template:
      src: template/top.j2
      dest: /srv/salt/top.sls
      mode: '0644'
    notify:
      - Restart salt-master service
    tags: top

  - name: Placing configuration files
    template:
      src: template/master_conf.j2
      dest: /etc/salt/master.d/file_gitfs.conf
      mode: '0644'
    notify:
      - Restart salt-master service

  - name: Install gitpython through salt-pip
    shell:
      cmd: salt-pip install gitpython

  - name: Placing pillar configuration files
    template:
      src: template/pillar_conf.j2
      dest: /etc/salt/master.d/pillar.conf
      mode: '0644'
    notify:
      - Restart salt-master service

  - name: Set auto-accept for minions in salt-master
    lineinfile:
      path: /etc/salt/master
      regexp: '^#auto_accept:'
      line: 'auto_accept: True'
    notify:
      - Restart salt-master service

  tags:
    - salt
