---
- hosts: suse-mast
  become: true
  gather_facts: true
  ignore_errors: true

  tasks:
  - name: create physical network for all computes
    command:
      cmd: 'incus network create uplink --target="{{ item }}"'
    with_items:
      - suse-mast
      - suse-com1
      - suse-com2
      - suse-com3

  - name: initialize uplink networks
    command:
      cmd: 'incus network create uplink'
