---
# set user and public key
# you might to install sshpass pkg
# ansible-playbook -i inventories/hosts users.yml -l suse \
#         -u masum --ask-pass --ask-become-pass
- hosts: all
  become: yes
  gather_facts: yes

  tasks:
  - name: Adding user
    user:
      name: "{{ username }}"
      state: present
  
  - name: Adding Public key for user
    authorized_key:
      user: "{{ username }}"
      state: present
      key: "{{ item }}"
    with_items:
      - "{{ public_key }}"

  - name: Install packages sudo and ssh in CentOS
    yum:
      name: [ 'sudo', 'openssh-server' ]
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: Install sudo and ssh in Ubuntu
    apt:
      name: [ 'sudo', 'openssh-server' ]
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Install packages sudo and ssh in OpenSuse
    zypper:
      name: [ 'sudo',
        'openssh-server' ]
      state: latest
    when: ansible_os_family == "Suse"

  - name: Install packages sudo and ssh in freebsd
    pkgng:
      name: [ 'sudo',
        'openssh-server' ]
      state: latest
    when: ansible_distribution == "FreeBSD"

  - name: Touching user file in /etc/sudoers.d in CentOS or Ubuntu or Opensuse
    file:
      path: /etc/sudoers.d/10_{{ username }}
      state: touch
    when: ansible_distribution == "CentOS" or
          ansible_distribution == "Ubuntu" or
          ansible_os_family == "Suse"

  - name: Touching user file in /etc/sudoers.d in FreeBSD
    file:
      path: /usr/local/etc/sudoers.d/10_{{ username }}
      state: touch
    when: ansible_distribution == "FreeBSD"

  - name: Giving sudo right with no passwd to user in CentOS or Ubuntu or Opensuse
    lineinfile:
      path: /etc/sudoers.d/10_{{ username }}
      line: "{{ username }} ALL=(ALL) NOPASSWD: ALL"
    when: ansible_distribution == "CentOS" or
          ansible_distribution == "Ubuntu" or
          ansible_os_family == "Suse"

  - name: Giving sudo right with no passwd to user in FreeBSD
    lineinfile:
      path: /usr/local/etc/sudoers.d/10_{{ username }}
      line: "{{ username }} ALL=(ALL) NOPASSWD: ALL"
    when: ansible_distribution == "FreeBSD"

  - name: Run openssh-server
    service:
      name: sshd
      enabled: true
      state: started
