---
dns1: 8.8.8.8
ipv4_address: "192.168.3.1/24"
ipv4_ranges: "192.168.3.10-192.168.3.250"

incus_hosts:
  - name: saltmaster
    os: alma9-packer
  - name: sys-deb12-dev2
    os: debian12-packer
  - name: sys-alma9-dev2
    os: alma9-packer
  - name: sys-ubu22-dev2
    os: ubu22-packer
  - name: sys-ubu24-dev2
    os: ubu24-packer
