---
user: "masum"
git_username: "masumndc1"
git_repo: "puppet-control"
hostname: puppetserver
puppet_server: "puppetserver.incus"
deb_package:
  - tree
  - openjdk-11-jdk
  - python3-pip
  - net-tools
  - iputils-ping
  - git
  - vim
  - wget
  - gcc
  - gpg
  - ntp
  - ntpdate
  - puppet
  - puppet-master
  - firewalld
  - python3-firewall
rpm_package:
  - epel-release
  - tree
  - net-tools
  - chrony
  - python3-libselinux
  - python3-firewall
  - firewalld
  - selinux-policy
port:
  - "8140/tcp"
puppet_rpm_key: "https://yum.puppet.com/RPM-GPG-KEY-puppet"
puppet7_rpm_el8: "https://yum.puppet.com/puppet7/el/8/x86_64/puppet7-release-7.0.0-1.el8.noarch.rpm"
puppet7_server_el8: "https://yum.puppet.com/puppet7/el/8/x86_64/puppetserver-7.0.0-1.el8.noarch.rpm"
puppet_gpg_key_debian: "https://apt.puppet.com/puppet7-release-bullseye.deb"
puppet_gpg_key_ubu20: "https://apt.puppet.com/puppet7-release-focal.deb"
java_orig_args: "JAVA_ARGS=\"-Xms2g -Xmx2g -Djruby.logger.class=com.puppetlabs.jruby_utils.jruby.Slf4jLogger\""
java_replace_args: "JAVA_ARGS=\"-Xms512m -Xmx512m -Djruby.logger.class=com.puppetlabs.jruby_utils.jruby.Slf4jLogger\""
