---
hostname: saltmaster
deb_package:
  - openjdk-11-jdk
  - python3-pip
  - net-tools
  - iputils-ping
  - git
  - vim
  - wget
  - gcc
  - gpg

salt_package:
  - salt-master
  - salt-ssh
  - salt-syndic
  - salt-cloud
  - salt-api
  - git
  - firewalld
  - python-pygit2

salt_minion_package:
  - salt-minion

salt_port:
  - "4505/tcp"
  - "4506/tcp"

salt_key_url: https://repo.saltproject.io/py3/ubuntu/20.04/amd64/latest/salt-archive-keyring.gpg
salt_repo_url: deb https://repo.saltproject.io/py3/ubuntu/20.04/amd64/latest focal main

centos_salt_key: https://repo.saltproject.io/salt/py3/redhat/9/arm64/SALT-PROJECT-GPG-PUBKEY-2023.pub
centos_repo_url: https://repo.saltproject.io/salt/py3/redhat/9/arm64/latest.repo

interface1: ens160

git_username: masumndc1
git_repo: puppet-control
