---
hostname: saltmaster
deb_package:
  - firewalld
  - python3-pip
  - net-tools
  - iputils-ping
  - git
  - vim
  - wget
  - gcc
  - gpg

salt_package:
  - git
  - firewalld
  - python3-pygit2
  - salt-master
  - salt-ssh
  - salt-syndic
  - salt-cloud
  - salt-api

centos_pkg:
  - epel-release
  - python3-pygit2
  - python3-pygithub
  - python3-PyGithub
  - python3-GitPython

suse_pkg:
  - python39-PyGithub

salt_port:
  - "4505/tcp"
  - "4506/tcp"

deb_key_url: https://packages.broadcom.com/artifactory/api/security/keypair/SaltProjectKey/public
deb_repo_url: https://github.com/saltstack/salt-install-guide/releases/latest/download/salt.sources

centos_repo_url: https://repo.saltproject.io/salt/py3/redhat/9/arm64/latest
centos_salt_key: https://repo.saltproject.io/salt/py3/redhat/9/arm64/latest/SALT-PROJECT-GPG-PUBKEY-2023.pub

interface1: ens160

git_username: masumndc1
git_repo: puppet-control
