---
hostname: saltmaster
deb_package:
  - openjdk-11-jdk
  - python3-pip
  - net-tools
  - iputils-ping
  - git
  - vim
  - wget
  - gcc
  - gpg

salt_package:
  - git
  - firewalld
  - python-pygit2
  - salt-master
  - salt-ssh
  - salt-syndic
  - salt-cloud
  - salt-api

centos_pkg:
  - epel-release
  - python3-pygit2
  - python3-pygithub
  - python3-PyGithub
  - python3-GitPython

suse_pkg:
  - python39-PyGithub

salt_port:
  - "4505/tcp"
  - "4506/tcp"

deb_key_url: https://repo.saltproject.io/py3/ubuntu/20.04/amd64/latest/salt-archive-keyring.gpg
deb_repo_url: deb https://repo.saltproject.io/py3/ubuntu/20.04/amd64/latest focal main

centos_repo_url: https://repo.saltproject.io/salt/py3/redhat/9/arm64/latest
centos_salt_key: https://repo.saltproject.io/salt/py3/redhat/9/arm64/latest/SALT-PROJECT-GPG-PUBKEY-2023.pub

interface1: ens160

git_username: masumndc1
git_repo: puppet-control
