# puppet agent configuraiton on freebsd
# here we will install puppet agent 5 as our
# server running on centos7.0 is version of 5
- hosts: agent
  become: yes
  gather_facts: yes

  tasks:
  - name: Install puppet agent
    pkgng: 
      name: puppet5
      state: present
    when: ansible_distribution == "FreeBSD"
    
  - name: Enabling entry in /etc/rc.conf
    lineinfile:
      path: /etc/rc.conf
      line: puppet_enable="YES"
    
  - name: Creating puppet.conf file for agent
    template:
      src: puppet.conf.j2
      dest: /usr/local/etc/puppet/puppet.conf
      mode: u=rw,g=r,o=r

  - name: Enable puppet agent service
    service:
      name: puppet
      state: started
