---
# this yml will set hostname
- hosts: all
  become: yes
  gather_facts: yes

  tasks:
  - name: Set up hostname
    hostname:
      name: "{{ hostname }}"
    tags: hostname

  - name: Install locales
    apt:
      name: [ 'locales',
        'locales-all']
      state: present
      update_cache: yes
    when: ansible_distribution == "Debian"
    tags: locales
