---
- hosts: all
  become: true
  gather_facts: true
  ignore_errors: true


  tasks:
    - name: Install some required packages
      apt:
        name: [
          'gnupg',
          'neovim',
          'python3-pynvim'
          ]
        state: latest
        update_cache: true
      when: ansible_distribution == 'Debian' or
        ansible_distribution == 'Ubuntu'
