---
- hosts: secs
  become: true
  gather_facts: true

  tasks:
    - name: Install openscap
      apt:
        name: ['openscap-scanner', 'ssg-base', 'ssg-debderived', 'openscap-utils']
        state: present
        update_cache: true
      when: ansible_distribution == 'Ubuntu'

    - name: Install some supported packages
      apt:
        name: ['aide']
        state: present
        update_cache: yes
      when: ansible_distribution == 'Ubuntu'
