---
# set user and public key
# you might to install sshpass pkg
# example:
# ansible-playbook -i inventories/hosts users.yml -l suse \
#        -u masum --ask-pass --ask-become-pass
- hosts: all
  become: yes
  gather_facts: yes
  ignore_errors: true

  tasks:
  - name: Adding user
    user:
      name: "{{ username }}"
      state: present

  - name: Adding Public key for user
    authorized_key:
      user: "{{ username }}"
      state: present
      key: "{{ item }}"
    with_items:
      - "{{ public_key }}"

  - name: Install packages sudo and ssh
    package:
      name: [ 'sudo', 'openssh-server', 'ansible' ]
      state: latest
      update_cache: yes
    when: ansible_os_family == "Redhat" or
      ansible_os_family == "Debian" or
      ansible_os_family == "Suse" or
      ansible_distribution == "FreeBSD"
    tags: pkg

  - name: Giving sudo right with no passwd to user in CentOS Ubuntu Opensuse
    lineinfile:
      path: /etc/sudoers.d/10_{{ username }}
      line: "{{ username }} ALL=(ALL) NOPASSWD: ALL"
      create: yes
      state: present
    when: ansible_os_family == "Redhat" or
      ansible_os_family == "Debian" or
      ansible_os_family == "Suse" or
      ansible_distribution == "FreeBSD"

  - name: Giving sudo right with no passwd to user in FreeBSD
    lineinfile:
      path: /usr/local/etc/sudoers.d/10_{{ username }}
      line: "{{ username }} ALL=(ALL) NOPASSWD: ALL"
    when: ansible_distribution == "FreeBSD"

  - name: Run openssh-server
    service:
      name: sshd
      enabled: true
      state: started
