---
hostname: worker
deb_package:
  - openjdk-11-jdk
  - python3-pip
  - net-tools
  - iputils-ping
  - git
  - vim
  - wget
  - gcc
  - gpg

java_args: "JAVA_ARGS=\"-Xms1g -Xmx1g -Djruby.logger.class=com.puppetlabs.jruby_utils.jruby.Slf4jLogger\""

hosts_line: "192.168.20.167 puppetmaster puppet"
